// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW0w8cX1CrApaNJk7sdTOsxGDngodAw7I',
    appId: '1:5538162811:web:89f4d76c0006260b745ade',
    messagingSenderId: '5538162811',
    projectId: 'chatfire-28e34',
    authDomain: 'chatfire-28e34.firebaseapp.com',
    storageBucket: 'chatfire-28e34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkL4wr88G7Sexm_8CUF785u6WVLy9xMIQ',
    appId: '1:5538162811:android:4da0918c679b0375745ade',
    messagingSenderId: '5538162811',
    projectId: 'chatfire-28e34',
    storageBucket: 'chatfire-28e34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDteUqO9IL-n9z4Hp62Gh8o7GQS7bwvRgI',
    appId: '1:5538162811:ios:ea6435d275bb5b6e745ade',
    messagingSenderId: '5538162811',
    projectId: 'chatfire-28e34',
    storageBucket: 'chatfire-28e34.appspot.com',
    androidClientId: '5538162811-j77qpo75t799bdtnipa0vfadtsp2lphn.apps.googleusercontent.com',
    iosClientId: '5538162811-d4akqgcl7hret6ktg610sag9vh13dbs7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatfire',
  );
}
